[package]
name = "call_softfloat"
version = "0.1.0"
authors = ["SoyaOhnishi <ohnishi.soya@arc.cs.okayama-u.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
